### ISSUE TITLE
Remove Javascript from Smilies and Post Help box, and make Smilies box extended by default

### ISSUE THREAD

**Issue by the-r3dacted** [Eclipse-Community/eBoard2#15]
If removing Javascript breaks the post help in some way, it can be moved elsewhere, above or below the post.

**Comment by ghost** [comment]
Have you even read the code you're talking about? The fact this has 'help wanted' on it actually made me burst out laughing because of how ridiculously easy this would be...

... I'm not even going to fix this for you. I want you to at least try to work this out before making issue requests, and that involves at the bare minimum just looking at the part of the code in question (which is either in lib/layout,php or lib/snippets.php if I recall correctly, ABXD 2 is a lot less organised in terms of where functions are, but please, at the very least just look - and search the repo for function names and whatnot if need be - beforehand) 😛 

Besides, it's funny being able to belittle you to the bitter end for being a lazy sod in what can only be described as sheer hypocrisy on my part :heart:

**Comment by the-r3dacted** [comment]
I did look for it at some point, didn't find it, so I made an issue. Or maybe I found it and didn't know how to un-JS it. Either way I didn't know what to do so I made an issue.
